services:
  # MariaDB Database
  db:
    image: mariadb:11.4
    container_name: ustroy_db
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - ustroy_network
    healthcheck:
      test: ["CMD", "healthcheck.sh", "--connect", "--innodb_initialized"]
      start_period: 10s
      start_interval: 10s
      interval: 1m
      timeout: 5s
      retries: 3

  # WordPress
  wordpress:
    image: wordpress:6.7-php8.3-fpm
    container_name: ustroy_wordpress
    restart: unless-stopped
    depends_on:
      db:
        condition: service_healthy
    environment:
      WORDPRESS_DB_HOST: ${WORDPRESS_DB_HOST}
      WORDPRESS_DB_NAME: ${WORDPRESS_DB_NAME}
      WORDPRESS_DB_USER: ${WORDPRESS_DB_USER}
      WORDPRESS_DB_PASSWORD: ${WORDPRESS_DB_PASSWORD}
      WORDPRESS_CONFIG_EXTRA: |
        define('WP_HOME', '${WORDPRESS_SITE_URL}');
        define('WP_SITEURL', '${WORDPRESS_SITE_URL}');
        define('FORCE_SSL_ADMIN', true);
        if (isset($$_SERVER['HTTP_X_FORWARDED_PROTO']) && $$_SERVER['HTTP_X_FORWARDED_PROTO'] === 'https') {
          $$_SERVER['HTTPS'] = 'on';
        }
    volumes:
      - wordpress_data:/var/www/html
      - ./wp-config-extra.php:/var/www/html/wp-config-extra.php
    networks:
      - ustroy_network
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:9000/ping || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3

  # Nginx
  nginx:
    image: nginx:1.27-alpine
    container_name: ustroy_nginx
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/conf.d:/etc/nginx/conf.d:ro
      - wordpress_data:/var/www/html:ro
      - certbot_www:/var/www/certbot:ro
      - certbot_conf:/etc/letsencrypt:ro
    depends_on:
      wordpress:
        condition: service_healthy
    networks:
      - ustroy_network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  # Certbot for SSL certificates
  certbot:
    image: certbot/certbot:v2.11.0
    container_name: ustroy_certbot
    volumes:
      - certbot_www:/var/www/certbot
      - certbot_conf:/etc/letsencrypt
    command: certonly --webroot --webroot-path=/var/www/certbot --email i.tarchevsky@yandex.ru --agree-tos --no-eff-email -d ustroy.webtm.ru -d panel.ustroy.webtm.ru
    networks:
      - ustroy_network
    profiles:
      - ssl

  # Next.js (запускается отдельно)
  nextjs:
    build:
      context: .
      target: production
    container_name: ustroy_nextjs
    restart: unless-stopped
    environment:
      REVALIDATE_SECRET: ${REVALIDATE_SECRET}
      WORDPRESS_GRAPHQL_ENDPOINT: ${WORDPRESS_GRAPHQL_ENDPOINT}
    expose:
      - "3000"
    networks:
      - ustroy_network
    profiles:
      - nextjs
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:3000/api/health || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3

volumes:
  db_data:
  wordpress_data:
  certbot_www:
  certbot_conf:

networks:
  ustroy_network:
    driver: bridge
