services:
  nginx:
    image: nginx:1.25-alpine
    profiles: ["acme", "full"]
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - certbot-etc:/etc/letsencrypt
      - certbot-var:/var/lib/letsencrypt
      - ./public:/usr/share/nginx/html:ro
      - wp_data:/var/www/html:ro
    ports:
      - '80:80'
      - '443:443'
    networks:
      - web

  certbot:
    image: certbot/certbot
    profiles: ["acme", "full"]
    volumes:
      - certbot-etc:/etc/letsencrypt
      - certbot-var:/var/lib/letsencrypt
      - ./public:/usr/share/nginx/html
    entrypoint: /bin/sh -c "trap exit TERM; while :; do certbot renew --webroot -w /usr/share/nginx/html --quiet; sleep 7d; done"
    networks:
      - web

  certbot-init:
    image: certbot/certbot
    profiles: ["acme"]
    volumes:
      - certbot-etc:/etc/letsencrypt
      - certbot-var:/var/lib/letsencrypt
      - ./public:/usr/share/nginx/html
    entrypoint: >
      sh -c "certbot certonly --webroot -w /usr/share/nginx/html \
      --email i.tarchevsky@yandex.ru \
      --agree-tos \
      --no-eff-email \
      -d ustroy.webtm.ru -d panel.ustroy.webtm.ru"
    networks:
      - web
    depends_on:
      - nginx

  db:
    image: mariadb:11
    profiles: ["full"]
    restart: always
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - web
    ports:
      - '3306:3306'

  wordpress:
    image: wordpress:6.5-fpm-alpine
    profiles: ["full"]
    restart: always
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_NAME: ${WORDPRESS_DB_NAME}
      WORDPRESS_DB_USER: ${WORDPRESS_DB_USER}
      WORDPRESS_DB_PASSWORD: ${WORDPRESS_DB_PASSWORD}
      WORDPRESS_TABLE_PREFIX: wp_
      WORDPRESS_CONFIG_EXTRA: |
        define('WP_HOME', 'https://panel.ustroy.webtm.ru');
        define('WP_SITEURL', 'https://panel.ustroy.webtm.ru');
    env_file: .env
    depends_on:
      - db
    networks:
      - web
    expose:
      - 9000
    volumes:
      - wp_data:/var/www/html
      - ./docker/php-custom.ini:/usr/local/etc/php/conf.d/99-custom.ini:ro

  nextjs:
    build: .
    profiles: ["full"]
    env_file: .env
    restart: always
    networks:
      - web
    expose:
      - 3000

volumes:
  certbot-etc:
  certbot-var:
  db_data:
  wp_data:

networks:
  web:

volumes:
  certbot-etc:
  certbot-var:
  db_data:
  wp_data:

networks:
  web:
